# Download Path - "r"E:\Documents\Python\NMIC Downloader"
# File Naming Policy - script name + version + csv
base_url = "https://www.usgs.gov"
start_url = "https://www.usgs.gov/centers/national-minerals-information-center/commodity-statistics-and-information"

# NMIC Volume I - Commodity List
commodities_list = [
    "Abrasives, Manufactured",
    "Aggregates",
    "Alumina",
    "Aluminum",
    "Aluminum Oxide, Fused (Manufactured Abrasives)",
    "Antimony",
    "Arsenic",
    "Asbestos",
    "Barite",
    "Bauxite",
    "Bentonite (Clay Minerals)",
    "Beryllium",
    "Bismuth",
    "Boron",
    "Bromine",
    "Cadmium",
    "Calcium Carbonate (Crushed Stone, Lime)",
    "Cement",
    "Cesium",
    "Chromium",
    "Clay Minerals",
    "Coal Combustion Products",
    "Cobalt",
    "Copper",
    "Corundum (Manufactured Abrasives)",
    "Crushed Stone",
    "Diamond, Industrial",
    "Diatomite",
    "Dimension Stone",
    "Explosives",
    "Feldspar",
    "Ferroalloys",
    "Fluorspar",
    "Fuller's Earth (Clay Minerals)",
    "Gallium",
    "Garnet, Industrial",
    "Gemstones",
    "Germanium",
    "Gold",
    "Granite (Crushed Stone, Dimension Stone)",
    "Graphite",
    "Gypsum",
    "Hafnium",
    "Helium",
    "Ilmenite (Titanium Mineral Concentrates)",
    "Indium",
    "Iodine",
    "Iridium (Platinum-Group Metals)",
    "Iron Ore",
    "Iron Oxide Pigments",
    "Iron and Steel",
    "Iron and Steel Scrap",
    "Iron and Steel Slag",
    "Kaolin (Clay Minerals)",
    "Kyanite and Related Minerals",
    "Lead",
    "Lime",
    "Limestone (Crushed Stone, Dimension Stone)",
    "Lithium",
    "Magnesium",
    "Magnesium Compounds",
    "Manganese",
    "Marble (Crushed Stone, Dimension Stone)",
    "Mercury",
    "Mica",
    "Mining and Quarrying",
    "Molybdenum",
    "Mullite, Synthetic (Kyanite)",
    "Nepheline Syenite (Feldspar)",
    "Nickel",
    "Niobium",
    "Nitrogen",
    "Osmium (Platinum-Group Metals)",
    "Palladium (Platinum-Group Metals)",
    "Peat",
    "Perlite",
    "Phosphate Rock",
    "Platinum-Group Metals",
    "Potash",
    "Pumice and Pumicite",
    "Pyrophyllite (Talc)",
    "Quartz Crystal (Silica)",
    "Rare Earths",
    "Recycling",
    "Rhenium",
    "Rhodium (Platinum-Group Metals)",
    "Rubidium (Cesium)",
    "Ruthenium (Platinum-Group Metals)",
    "Rutile (Titanium Mineral Concentrates)",
    "Salt",
    "Sand and Gravel, Construction",
    "Sand and Gravel, Industrial (Silica)",
    "Sandstone (Crushed Stone, Dimension Stone)",
    "Scandium (Rare Earths)",
    "Selenium",
    "Shell (Gemstones)",
    "Silica",
    "Silicon",
    "Silicon Carbide (Manufactured Abrasives)",
    "Silver",
    "Slate (Crushed Stone, Dimension Stone)",
    "Soda Ash",
    "Sodium Sulfate",
    "Statistical Summary",
    "Steel",
    "Stone, Crushed",
    "Stone, Dimension",
    "Strontium",
    "Sulfur",
    "Survey Methods",
    "Talc",
    "Tantalum",
    "Tellurium",
    "Thallium",
    "Thorium",
    "Tin",
    "Titanium",
    "Titanium Dioxide",
    "Titanium Mineral Concentrates",
    "Traprock (Crushed Stone)",
    "Tripoli (Silica)",
    "Tungsten",
    "Vanadium",
    "Vermiculite",
    "Wollastonite",
    "Yttrium (Rare Earths)",
    "Zeolites",
    "Zinc",
    "Zirconium",
]

# NMIC Volume I - Commodity groups
commodity_groups = ['A-F', 'G-L', 'M-S', 'T-Z']

# Auto-generated config with full URLs (commodities_url)
commodities_url = {
    "Abrasives, Manufactured": "https://www.usgs.gov/centers/national-minerals-information-center/manufactured-abrasives-statistics-and-information",
    "Aggregates": "https://www.usgs.gov/centers/national-minerals-information-center/natural-aggregates-statistics-and-information",
    "Alumina": "https://www.usgs.gov/centers/national-minerals-information-center/bauxite-and-alumina-statistics-and-information",
    "Aluminum": "https://www.usgs.gov/centers/national-minerals-information-center/aluminum-statistics-and-information",
    "Aluminum Oxide, Fused (Manufactured Abrasives)": "https://www.usgs.gov/centers/national-minerals-information-center/abrasives-statistics-and-information",
    "Antimony": "https://www.usgs.gov/centers/national-minerals-information-center/antimony-statistics-and-information",
    "Arsenic": "https://www.usgs.gov/centers/national-minerals-information-center/arsenic-statistics-and-information",
    "Asbestos": "https://www.usgs.gov/centers/national-minerals-information-center/asbestos-statistics-and-information",
    "Barite": "https://www.usgs.gov/centers/national-minerals-information-center/barite-statistics-and-information",
    "Bauxite": "https://www.usgs.gov/centers/nmic/bauxite-and-alumina-statistics-and-information",
    "Bentonite (Clay Minerals)": "https://www.usgs.gov/centers/national-minerals-information-center/clays-statistics-and-information",
    "Beryllium": "https://www.usgs.gov/centers/national-minerals-information-center/beryllium-statistics-and-information",
    "Bismuth": "https://www.usgs.gov/centers/national-minerals-information-center/bismuth-statistics-and-information",
    "Boron": "https://www.usgs.gov/centers/national-minerals-information-center/boron-statistics-and-information",
    "Bromine": "https://www.usgs.gov/centers/national-minerals-information-center/bromine-statistics-and-information",
    "Cadmium": "https://www.usgs.gov/centers/national-minerals-information-center/cadmium-statistics-and-information",
    "Calcium Carbonate (Crushed Stone, Lime)": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Cement": "https://www.usgs.gov/centers/national-minerals-information-center/cement-statistics-and-information",
    "Cesium": "https://www.usgs.gov/centers/national-minerals-information-center/cesium-and-rubidium-statistics-and-information",
    "Chromium": "https://www.usgs.gov/centers/national-minerals-information-center/chromium-statistics-and-information",
    "Clay Minerals": "https://www.usgs.gov/centers/national-minerals-information-center/clays-statistics-and-information",
    "Coal Combustion Products": "https://www.usgs.gov/centers/national-minerals-information-center/coal-combustion-products-statistics-and-information",
    "Cobalt": "https://www.usgs.gov/centers/national-minerals-information-center/cobalt-statistics-and-information",
    "Copper": "https://www.usgs.gov/centers/national-minerals-information-center/copper-statistics-and-information",
    "Corundum (Manufactured Abrasives)": "https://www.usgs.gov/centers/national-minerals-information-center/abrasives-statistics-and-information",
    "Crushed Stone": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Diamond, Industrial": "https://www.usgs.gov/centers/national-minerals-information-center/industrial-diamonds-statistics-and-information",
    "Diatomite": "https://www.usgs.gov/centers/national-minerals-information-center/diatomite-statistics-and-information",
    "Dimension Stone": "https://www.usgs.gov/centers/national-minerals-information-center/dimension-stone-statistics-and-information",
    "Explosives": "https://www.usgs.gov/centers/national-minerals-information-center/explosives-statistics-and-information",
    "Feldspar": "https://www.usgs.gov/centers/national-minerals-information-center/feldspar-statistics-and-information",
    "Ferroalloys": "https://www.usgs.gov/centers/national-minerals-information-center/ferroalloys-statistics-and-information",
    "Fluorspar": "https://www.usgs.gov/centers/national-minerals-information-center/fluorspar-statistics-and-information",
    "Fuller's Earth (Clay Minerals)": "https://www.usgs.gov/centers/national-minerals-information-center/clays-statistics-and-information",
    "Gallium": "https://www.usgs.gov/centers/national-minerals-information-center/gallium-statistics-and-information",
    "Garnet, Industrial": "https://www.usgs.gov/centers/national-minerals-information-center/garnet-statistics-and-information",
    "Gemstones": "https://www.usgs.gov/centers/national-minerals-information-center/gemstones-statistics-and-information",
    "Germanium": "https://www.usgs.gov/centers/national-minerals-information-center/germanium-statistics-and-information",
    "Gold": "https://www.usgs.gov/centers/national-minerals-information-center/gold-statistics-and-information",
    "Granite (Crushed Stone, Dimension Stone)": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Graphite": "https://www.usgs.gov/centers/national-minerals-information-center/graphite-statistics-and-information",
    "Gypsum": "https://www.usgs.gov/centers/national-minerals-information-center/gypsum-statistics-and-information",
    "Hafnium": "https://www.usgs.gov/centers/national-minerals-information-center/hafnium-statistics-and-information",
    "Helium": "https://www.usgs.gov/centers/national-minerals-information-center/helium-statistics-and-information",
    "Ilmenite (Titanium Mineral Concentrates)": "https://www.usgs.gov/centers/national-minerals-information-center/titanium-mineral-concentrates-statistics-and-information",
    "Indium": "https://www.usgs.gov/centers/national-minerals-information-center/indium-statistics-and-information",
    "Iodine": "https://www.usgs.gov/centers/national-minerals-information-center/iodine-statistics-and-information",
    "Iridium (Platinum-Group Metals)": "https://www.usgs.gov/centers/national-minerals-information-center/platinum-group-metals-statistics-and-information",
    "Iron Ore": "https://www.usgs.gov/centers/national-minerals-information-center/iron-ore-statistics-and-information",
    "Iron Oxide Pigments": "https://www.usgs.gov/centers/national-minerals-information-center/iron-oxide-pigments-statistics-and-information",
    "Iron and Steel": "https://www.usgs.gov/centers/national-minerals-information-center/iron-and-steel-statistics-and-information",
    "Iron and Steel Scrap": "https://www.usgs.gov/centers/national-minerals-information-center/iron-and-steel-scrap-statistics-and-information",
    "Iron and Steel Slag": "https://www.usgs.gov/centers/national-minerals-information-center/iron-and-steel-slag-statistics-and-information",
    "Kaolin (Clay Minerals)": "https://www.usgs.gov/centers/national-minerals-information-center/clays-statistics-and-information",
    "Kyanite and Related Minerals": "https://www.usgs.gov/centers/national-minerals-information-center/kyanite-and-related-minerals-statistics-and-information",
    "Lead": "https://www.usgs.gov/centers/national-minerals-information-center/lead-statistics-and-information",
    "Lime": "https://www.usgs.gov/centers/national-minerals-information-center/lime-statistics-and-information",
    "Limestone (Crushed Stone, Dimension Stone)": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Lithium": "https://www.usgs.gov/centers/national-minerals-information-center/lithium-statistics-and-information",
    "Magnesium": "https://www.usgs.gov/centers/national-minerals-information-center/magnesium-statistics-and-information",
    "Magnesium Compounds": "https://www.usgs.gov/centers/national-minerals-information-center/magnesium-compounds-statistics-and-information",
    "Manganese": "https://www.usgs.gov/centers/national-minerals-information-center/manganese-statistics-and-information",
    "Marble (Crushed Stone, Dimension Stone)": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Mercury": "https://www.usgs.gov/centers/national-minerals-information-center/mercury-statistics-and-information",
    "Mica": "https://www.usgs.gov/centers/national-minerals-information-center/mica-statistics-and-information",
    "Mining and Quarrying": "https://www.usgs.gov/centers/national-minerals-information-center/mining-and-quarrying-statistics-and-information",
    "Molybdenum": "https://www.usgs.gov/centers/national-minerals-information-center/molybdenum-statistics-and-information",
    "Mullite, Synthetic (Kyanite)": "https://www.usgs.gov/centers/national-minerals-information-center/kyanite-and-related-minerals-statistics-and-information",
    "Nepheline Syenite (Feldspar)": "https://www.usgs.gov/centers/national-minerals-information-center/feldspar-statistics-and-information",
    "Nickel": "https://www.usgs.gov/centers/national-minerals-information-center/nickel-statistics-and-information",
    "Niobium": "https://www.usgs.gov/centers/national-minerals-information-center/niobium-and-tantalum-statistics-and-information",
    "Nitrogen": "https://www.usgs.gov/centers/national-minerals-information-center/nitrogen-statistics-and-information",
    "Osmium (Platinum-Group Metals)": "https://www.usgs.gov/centers/national-minerals-information-center/platinum-group-metals-statistics-and-information",
    "Palladium (Platinum-Group Metals)": "https://www.usgs.gov/centers/national-minerals-information-center/platinum-group-metals-statistics-and-information",
    "Peat": "https://www.usgs.gov/centers/national-minerals-information-center/peat-statistics-and-information",
    "Perlite": "https://www.usgs.gov/centers/national-minerals-information-center/perlite-statistics-and-information",
    "Phosphate Rock": "https://www.usgs.gov/centers/national-minerals-information-center/phosphate-rock-statistics-and-information",
    "Platinum-Group Metals": "https://www.usgs.gov/centers/national-minerals-information-center/platinum-group-metals-statistics-and-information",
    "Potash": "https://www.usgs.gov/centers/national-minerals-information-center/potash-statistics-and-information",
    "Pumice and Pumicite": "https://www.usgs.gov/centers/national-minerals-information-center/pumice-and-pumicite-statistics-and-information",
    "Pyrophyllite (Talc)": "https://www.usgs.gov/centers/national-minerals-information-center/talc-and-pyrophyllite-statistics-and-information",
    "Quartz Crystal (Silica)": "https://www.usgs.gov/centers/national-minerals-information-center/silica-statistics-and-information",
    "Rare Earths": "https://www.usgs.gov/centers/national-minerals-information-center/rare-earths-statistics-and-information",
    "Recycling": "https://www.usgs.gov/centers/national-minerals-information-center/recycling-statistics-and-information",
    "Rhenium": "https://www.usgs.gov/centers/national-minerals-information-center/rhenium-statistics-and-information",
    "Rhodium (Platinum-Group Metals)": "https://www.usgs.gov/centers/national-minerals-information-center/platinum-group-metals-statistics-and-information",
    "Rubidium (Cesium)": "https://www.usgs.gov/centers/national-minerals-information-center/cesium-and-rubidium-statistics-and-information",
    "Ruthenium (Platinum-Group Metals)": "https://www.usgs.gov/centers/national-minerals-information-center/platinum-group-metals-statistics-and-information",
    "Rutile (Titanium Mineral Concentrates)": "https://www.usgs.gov/centers/national-minerals-information-center/titanium-mineral-concentrates-statistics-and-information",
    "Salt": "https://www.usgs.gov/centers/national-minerals-information-center/salt-statistics-and-information",
    "Sand and Gravel, Construction": "https://www.usgs.gov/centers/national-minerals-information-center/sand-and-gravel-statistics-and-information",
    "Sand and Gravel, Industrial (Silica)": "https://www.usgs.gov/centers/national-minerals-information-center/silica-statistics-and-information",
    "Sandstone (Crushed Stone, Dimension Stone)": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Scandium (Rare Earths)": "https://www.usgs.gov/centers/national-minerals-information-center/rare-earths-statistics-and-information",
    "Selenium": "https://www.usgs.gov/centers/national-minerals-information-center/selenium-and-tellurium-statistics-and-information",
    "Shell (Gemstones)": "https://www.usgs.gov/centers/national-minerals-information-center/gemstones-statistics-and-information",
    "Silica": "https://www.usgs.gov/centers/national-minerals-information-center/silica-statistics-and-information",
    "Silicon": "https://www.usgs.gov/centers/national-minerals-information-center/silicon-statistics-and-information",
    "Silicon Carbide (Manufactured Abrasives)": "https://www.usgs.gov/centers/national-minerals-information-center/abrasives-statistics-and-information",
    "Silver": "https://www.usgs.gov/centers/national-minerals-information-center/silver-statistics-and-information",
    "Slate (Crushed Stone, Dimension Stone)": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Soda Ash": "https://www.usgs.gov/centers/national-minerals-information-center/soda-ash-statistics-and-information",
    "Sodium Sulfate": "https://www.usgs.gov/centers/national-minerals-information-center/sodium-sulfate-statistics-and-information",
    "Statistical Summary": "https://www.usgs.gov/centers/national-minerals-information-center/statistical-summary",
    "Steel": "https://www.usgs.gov/centers/national-minerals-information-center/steel-statistics-and-information",
    "Stone, Crushed": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Stone, Dimension": "https://www.usgs.gov/centers/national-minerals-information-center/dimension-stone-statistics-and-information",
    "Strontium": "https://www.usgs.gov/centers/national-minerals-information-center/strontium-statistics-and-information",
    "Sulfur": "https://www.usgs.gov/centers/national-minerals-information-center/sulfur-statistics-and-information",
    "Survey Methods": "https://www.usgs.gov/centers/national-minerals-information-center/survey-methods",
    "Talc": "https://www.usgs.gov/centers/national-minerals-information-center/talc-and-pyrophyllite-statistics-and-information",
    "Tantalum": "https://www.usgs.gov/centers/national-minerals-information-center/niobium-and-tantalum-statistics-and-information",
    "Tellurium": "https://www.usgs.gov/centers/national-minerals-information-center/selenium-and-tellurium-statistics-and-information",
    "Thallium": "https://www.usgs.gov/centers/national-minerals-information-center/thallium-statistics-and-information",
    "Thorium": "https://www.usgs.gov/centers/national-minerals-information-center/thorium-statistics-and-information",
    "Tin": "https://www.usgs.gov/centers/national-minerals-information-center/tin-statistics-and-information",
    "Titanium": "https://www.usgs.gov/centers/national-minerals-information-center/titanium-statistics-and-information",
    "Titanium Dioxide": "https://www.usgs.gov/centers/national-minerals-information-center/titanium-statistics-and-information",
    "Titanium Mineral Concentrates": "https://www.usgs.gov/centers/national-minerals-information-center/titanium-mineral-concentrates-statistics-and-information",
    "Traprock (Crushed Stone)": "https://www.usgs.gov/centers/national-minerals-information-center/crushed-stone-statistics-and-information",
    "Tripoli (Silica)": "https://www.usgs.gov/centers/national-minerals-information-center/silica-statistics-and-information",
    "Tungsten": "https://www.usgs.gov/centers/national-minerals-information-center/tungsten-statistics-and-information",
    "Vanadium": "https://www.usgs.gov/centers/national-minerals-information-center/vanadium-statistics-and-information",
    "Vermiculite": "https://www.usgs.gov/centers/national-minerals-information-center/vermiculite-statistics-and-information",
    "Wollastonite": "https://www.usgs.gov/centers/national-minerals-information-center/wollastonite-statistics-and-information",
    "Yttrium (Rare Earths)": "https://www.usgs.gov/centers/national-minerals-information-center/rare-earths-statistics-and-information",
    "Zeolites": "https://www.usgs.gov/centers/national-minerals-information-center/zeolites-statistics-and-information",
    "Zinc": "https://www.usgs.gov/centers/national-minerals-information-center/zinc-statistics-and-information",
    "Zirconium": "https://www.usgs.gov/centers/national-minerals-information-center/zirconium-and-hafnium-statistics-and-information",
}

# NMIC Volume III - Region list
regions_list = [
    "Africa and Middle East", "Asia and Pacific", "Europe and Central Eurasia", "North and Central America", "South America",
]

# NMIC Volumne III - Region URLs
regions_url = {
    "Africa and the Middle East": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east",
    "Asia and the Pacific": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific",
    "Europe and Central Eurasia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia",
    "Latin America and Canada | North America, Central America, and the Caribbean": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america",
    "South America": "https://www.usgs.gov/centers/national-minerals-information-center/south-america"
}

# NMIC Volume III - Country List
countries_list = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Antarctica', 'Antigua and Barbuda',
    'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
    'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
    'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
    'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands',
    'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Colombia',
    'Comoros', 'Congo Brazzaville', 'Congo Kinshasa', 'Cook Islands', 'Costa Rica', 'Croatia',
    'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica',
    'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea',
    'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Falkland Islands', 'Faroe Islands',
    'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
    'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
    'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey',
    'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong',
    'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
    'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica',
    'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
    'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
    'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macau',
    'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
    'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
    'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat',
    'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
    'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
    'Niue', 'Norfolk Island', 'North Korea', 'North Macedonia', 'Northern Mariana Islands', 'Norway',
    'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea',
    'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland', 'Portugal',
    'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda',
    'Saint Barthelemy', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
    'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
    'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain',
    'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
    'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo',
    'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
    'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
    'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela',
    'Vietnam', 'Virgin Islands', 'Wallis and Futuna', 'Western Sahara', 'Yemen', 'Zambia',
    'Zimbabwe'
]

# NMIC Volume III - Country Listing & Country Code to Name Mapping
country_map = {
    "afg": "Afghanistan",
    "ago": "Angola",
    "alb": "Albania",
    "are": "United Arab Emirates",
    "arg": "Argentina",
    "arm": "Armenia",
    "aus": "Australia",
    "aut": "Austria",
    "aze": "Azerbaijan",
    "bdi": "Burundi",
    "bel": "Belgium",
    "ben": "Benin",
    "bfa": "Burkina Faso",
    "bgd": "Bangladesh",
    "bgr": "Bulgaria",
    "bhr": "Bahrain",
    "bih": "Bosnia and Herzegovina",
    "blr": "Belarus",
    "bol": "Bolivia",
    "bra": "Brazil",
    "brn": "Brunei",
    "btn": "Bhutan",
    "bwa": "Botswana",
    "caf": "Central African Republic",
    "can": "Canada",
    "che": "Switzerland",
    "chl": "Chile",
    "chn": "China",
    "civ": "Cote d'Ivoire",
    "cmr": "Cameroon",
    "cod": "Congo (Kinshasa)",
    "cog": "Congo (Brazzaville)",
    "col": "Colombia",
    "com": "Comoros",
    "cpv": "Cabo Verde",
    "cub": "Cuba",
    "cxr": "Christmas Island",
    "cyp": "Cyprus",
    "cze": "Czechia",
    "deu": "Germany",
    "dji": "Djibouti",
    "dnk": "Denmark",
    "dza": "Algeria",
    "ecu": "Ecuador",
    "egy": "Egypt",
    "eri": "Eritrea",
    "esh": "Western Sahara",
    "esp": "Spain",
    "est": "Estonia",
    "eth": "Ethiopia",
    "fin": "Finland",
    "fji": "Fiji",
    "fra": "France",
    "gab": "Gabon",
    "gbr": "United Kingdom",
    "geo": "Georgia",
    "gha": "Ghana",
    "gin": "Guinea",
    "gmb": "Gambia",
    "gnb": "Guinea-Bissau",
    "gnq": "Equatorial Guinea",
    "grc": "Greece",
    "guf": "French Guiana",
    "guy": "Guyana",
    "hkg": "Hong Kong",
    "hrv": "Croatia",
    "hun": "Hungary",
    "idn": "Indonesia",
    "ind": "India",
    "irl": "Ireland",
    "irn": "Iran",
    "irq": "Iraq",
    "isl": "Iceland",
    "isr": "Israel",
    "ita": "Italy",
    "jor": "Jordan",
    "jpn": "Japan",
    "kaz": "Kazakhstan",
    "ken": "Kenya",
    "kgc": "Kyrgyzstan",
    "khm": "Cambodia",
    "kor": "Korea, Republic of",
    "kwt": "Kuwait",
    "lao": "Laos",
    "lbn": "Lebanon",
    "lbr": "Liberia",
    "lby": "Libya",
    "lka": "Sri Lanka",
    "lso": "Lesotho",
    "ltu": "Lithuania",
    "lux": "Luxembourg",
    "lva": "Latvia",
    "mar": "Morocco",
    "mda": "Moldova",
    "mdg": "Madagascar",
    "mex": "Mexico",
    "mkd": "North Macedonia",
    "mli": "Mali",
    "mlt": "Malta",
    "mmr": "Burma",
    "mne": "Montenegro",
    "mng": "Mongolia",
    "moz": "Mozambique",
    "mrt": "Mauritania",
    "mus": "Mauritius",
    "mwi": "Malawi",
    "mys": "Malaysia",
    "nam": "Namibia",
    "ncl": "New Caledonia",
    "ner": "Niger",
    "nga": "Nigeria",
    "nld": "Netherlands",
    "nor": "Norway",
    "npl": "Nepal",
    "nru": "Nauru",
    "nzl": "New Zealand",
    "omn": "Oman",
    "pak": "Pakistan",
    "per": "Peru",
    "phl": "Philippines",
    "png": "Papua New Guinea",
    "pol": "Poland",
    "prk": "Korea, North",
    "prt": "Portugal",
    "pry": "Paraguay",
    "qat": "Qatar",
    "reu": "Reunion",
    "rou": "Romania",
    "rus": "Russia",
    "rwa": "Rwanda",
    "sau": "Saudi Arabia",
    "sdn": "Sudan",
    "sen": "Senegal",
    "sgp": "Singapore",
    "slb": "Solomon Islands",
    "sle": "Sierra Leone",
    "som": "Somalia",
    "srb": "Serbia",
    "ssd": "South Sudan",
    "stp": "Sao Tome and Principe",
    "sur": "Suriname",
    "svk": "Slovakia",
    "svn": "Slovenia",
    "swe": "Sweden",
    "swz": "Eswatini",
    "syc": "Seychelles",
    "syr": "Syria",
    "tcd": "Chad",
    "tgo": "Togo",
    "tha": "Thailand",
    "tjk": "Tajikistan",
    "tkm": "Turkmenistan",
    "tls": "Timor-Leste",
    "tun": "Tunisia",
    "tur": "Turkey",
    "twn": "Taiwan",
    "tza": "Tanzania",
    "uga": "Uganda",
    "ukr": "Ukraine",
    "ury": "Uruguay",
    "uzb": "Uzbekistan",
    "ven": "Venezuela",
    "vnm": "Vietnam",
    "xks": "Kosovo",
    "yem": "Yemen",
    "zaf": "South Africa",
    "zmb": "Zambia",
    "zwe": "Zimbabwe"
}

# NMIC Volume III - Country Groups Dictionary
country_grouping = {
    'Africa and the Middle East': [
        'Algeria', 'Angola', 'Bahrain', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon',
        'Cape Verde', 'Central African Republic', 'Chad', 'Comoros', 'Congo (Brazzaville)',
        'Congo (Kinshasa)', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Gabon',
        'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Iran', 'Iraq', 'Israel', 'Ivory Coast', 'Jordan',
        'Kenya', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali',
        'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Oman',
        'Qatar', 'Rwanda', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Seychelles', 'Sierra Leone',
        'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Swaziland', 'Syria', 'Tanzania', 'Togo',
        'Tunisia', 'Uganda', 'United Arab Emirates', 'Yemen', 'Zambia', 'Zimbabwe'
    ],
    'Asia and the Pacific': [
        'Afghanistan', 'Australia', 'Bangladesh', 'Bhutan', 'Brunei', 'Burma', 'Cambodia', 'China',
        'Fiji', 'India', 'Indonesia', 'Japan', 'Kiribati', 'Korea, North', 'Korea, South', 'Laos',
        'Malaysia', 'Maldives', 'Marshall Islands', 'Micronesia', 'Mongolia', 'Nauru', 'Nepal', 'New Zealand',
        'Pakistan', 'Palau', 'Papua New Guinea', 'Philippines', 'Samoa', 'Singapore', 'Solomon Islands',
        'Sri Lanka', 'Thailand', 'Timor-Leste', 'Tonga', 'Tuvalu', 'Vanuatu', 'Vietnam'
    ],
    'Europe and Central Eurasia': [
        'Albania', 'Andorra', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina',
        'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia',
        'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Kazakhstan', 'Kosovo', 'Kyrgyzstan',
        'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia', 'Malta', 'Moldova', 'Monaco',
        'Montenegro', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia',
        'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Tajikistan', 'Turkey', 'Turkmenistan',
        'Ukraine', 'United Kingdom', 'Uzbekistan', 'Vatican City'
    ],
    'Latin America and Canada | North America, Central America, and the Caribbean': [
        'Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica', 'Cuba', 'Dominica',
        'Dominican Republic', 'El Salvador', 'Grenada', 'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Mexico',
        'Nicaragua', 'Panama', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines',
        'Trinidad and Tobago'
    ],
    'South America': [
        'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru',
        'Suriname', 'Uruguay', 'Venezuela'
    ]
}
# Auto-generated config with full URLs (countries_url)
countries_url = {
    "Afghanistan": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#afg",
    "Albania": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#alb",
    "Algeria": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#dza",
    "Angola": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#ago",
    "Antarctica": "https://www.usgs.gov/centers/national-minerals-information-center/antarctica",
    "Antigua and Barbuda": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Argentina": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#arg",
    "Armenia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#arm",
    "Aruba": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Australia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#aus",
    "Austria": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#aut",
    "Azerbaijan": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#aze",
    "Bahamas": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Bahrain": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#bhr",
    "Bangladesh": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#bgd",
    "Barbados": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Belarus": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#blr",
    "Belgium": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#bel",
    "Belize": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#central-america",
    "Benin": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#ben",
    "Bermuda": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Bhutan": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#btn",
    "Bolivia": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#bol",
    "Bosnia and Herzegovina": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#bih",
    "Botswana": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#bwa",
    "Brazil": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#bra",
    "British Virgin Islands": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Brunei": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#brn",
    "Bulgaria": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#bgr",
    "Burkina Faso": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#bfa",
    "Burundi": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#bdi",
    "Cambodia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#khm",
    "Cameroon": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#cmr",
    "Canada": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#north-america",
    "Cape Verde": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#cpv",
    "Cayman Islands": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Central African Republic": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#caf",
    "Chad": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#tcd",
    "Chile": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#chl",
    "China": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#chn",
    "Christmas Island": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#cxr",
    "Colombia": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#col",
    "Comoros": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#com",
    "Congo Brazzaville": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#cog",
    "Congo Kinshasa": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#cod",
    "Cook Islands": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#cok",
    "Costa Rica": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#central-america",
    "Croatia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#hrv",
    "Cuba": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Cyprus": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#cyp",
    "Czech Republic": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#cze",
    "Denmark": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#dnk",
    "Djibouti": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#dji",
    "Dominica": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Dominican Republic": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "East Timor": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#tls",
    "Ecuador": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#ecu",
    "Egypt": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#egy",
    "El Salvador": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#central-america",
    "Equatorial Guinea": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#gnq",
    "Eritrea": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#eri",
    "Estonia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#est",
    "Eswatini": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#swz",
    "Ethiopia": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#eth",
    "Falkland Islands": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#south-america",
    "Faroe Islands": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#fro",
    "Fiji": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#fji",
    "Finland": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#fin",
    "France": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#fra",
    "French Guiana": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#pyf",
    "French Polynesia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#pyf",
    "Gabon": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#gab",
    "Gambia": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#gmb",
    "Georgia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#geo",
    "Germany": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#deu",
    "Ghana": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#gha",
    "Gibraltar": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#gib",
    "Greece": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#grc",
    "Greenland": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#grl",
    "Grenada": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Guadeloupe": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Guam": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#gum",
    "Guatemala": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#central-america",
    "Guernsey": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#ggg",
    "Guinea": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#gin",
    "Guinea-Bissau": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#gnb",
    "Guyana": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#guy",
    "Haiti": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Honduras": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#central-america",
    "Hong Kong": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#hkg",
    "Hungary": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#hun",
    "Iceland": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#isl",
    "India": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#ind",
    "Indonesia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#idn",
    "Iran": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#irn",
    "Iraq": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#irq",
    "Ireland": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#irl",
    "Isle of Man": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#imn",
    "Israel": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#isr",
    "Italy": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#ita",
    "Ivory Coast": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#civ",
    "Jamaica": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Japan": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#jpn",
    "Jersey": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#jey",
    "Jordan": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#jor",
    "Kazakhstan": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#kaz",
    "Kenya": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#ken",
    "Kiribati": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#kir",
    "Kuwait": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#kwt",
    "Kyrgyzstan": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#kgz",
    "Laos": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#lao",
    "Latvia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#lva",
    "Lebanon": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#lbn",
    "Lesotho": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#lso",
    "Liberia": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#lbr",
    "Libya": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#lby",
    "Liechtenstein": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#lie",
    "Lithuania": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#ltu",
    "Luxembourg": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#lux",
    "Macau": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#mac",
    "Madagascar": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#mdg",
    "Malawi": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#mwi",
    "Malaysia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#mys",
    "Maldives": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#mdv",
    "Mali": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#mli",
    "Malta": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#mlt",
    "Marshall Islands": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#mhl",
    "Martinique": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Mauritania": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#mrt",
    "Mauritius": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#mus",
    "Mayotte": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#myt",
    "Mexico": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#mex",
    "Micronesia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#fsm",
    "Moldova": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#mda",
    "Monaco": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#mco",
    "Mongolia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#mng",
    "Montenegro": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#mne",
    "Montserrat": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Morocco": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#mar",
    "Mozambique": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#moz",
    "Myanmar": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#mmr",
    "Namibia": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#nam",
    "Nauru": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#nru",
    "Nepal": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#npl",
    "Netherlands": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#nld",
    "New Caledonia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#ncl",
    "New Zealand": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#nzl",
    "Nicaragua": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#central-america",
    "Niger": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#ner",
    "Nigeria": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#nga",
    "Niue": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#niu",
    "Norfolk Island": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#nfk",
    "North Korea": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#prk",
    "North Macedonia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#mkd",
    "Northern Mariana Islands": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#mnp",
    "Norway": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#nor",
    "Oman": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#omn",
    "Pakistan": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#pak",
    "Palau": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#plw",
    "Palestine": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#pse",
    "Panama": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#central-america",
    "Papua New Guinea": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#png",
    "Paraguay": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#pry",
    "Peru": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#per",
    "Philippines": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#phl",
    "Pitcairn Islands": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#pcn",
    "Poland": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#pol",
    "Portugal": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#prt",
    "Puerto Rico": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Qatar": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#qat",
    "Reunion": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#reu",
    "Romania": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#rou",
    "Russia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#rus",
    "Rwanda": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#rwa",
    "Saint Barthelemy": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Saint Helena": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#shn",
    "Saint Kitts and Nevis": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Saint Lucia": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Saint Martin": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Saint Pierre and Miquelon": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#north-america",
    "Saint Vincent and the Grenadines": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Samoa": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#ws",
    "San Marino": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#smr",
    "Sao Tome and Principe": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#stp",
    "Saudi Arabia": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#sau",
    "Senegal": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#sen",
    "Serbia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#srb",
    "Seychelles": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#syc",
    "Sierra Leone": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#sle",
    "Singapore": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#sgp",
    "Slovakia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#svk",
    "Slovenia": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#svn",
    "Solomon Islands": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#slb",
    "Somalia": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#som",
    "South Africa": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#zaf",
    "South Korea": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#kor",
    "South Sudan": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#ssd",
    "Spain": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#esp",
    "Sri Lanka": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#lka",
    "Sudan": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#sdn",
    "Suriname": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#sur",
    "Sweden": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#swe",
    "Switzerland": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#che",
    "Syria": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#syr",
    "Taiwan": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#twn",
    "Tajikistan": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#tjk",
    "Tanzania": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#tza",
    "Thailand": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#tha",
    "Timor-Leste": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#tls",
    "Togo": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#tgo",
    "Tokelau": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#tkl",
    "Tonga": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#ton",
    "Trinidad and Tobago": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Tunisia": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#tun",
    "Turkey": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#tur",
    "Turkmenistan": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#tkm",
    "Turks and Caicos Islands": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Tuvalu": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#tuv",
    "Uganda": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#uga",
    "Ukraine": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#ukr",
    "United Arab Emirates": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#are",
    "United Kingdom": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#gbr",
    "United States": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#usa",
    "Uruguay": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#ury",
    "Uzbekistan": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#uzb",
    "Vanuatu": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#vut",
    "Vatican City": "https://www.usgs.gov/centers/national-minerals-information-center/europe-and-central-eurasia#vat",
    "Venezuela": "https://www.usgs.gov/centers/national-minerals-information-center/south-america#ven",
    "Vietnam": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#vnm",
    "Virgin Islands": "https://www.usgs.gov/centers/national-minerals-information-center/latin-america-and-canada-north-america-central-america#caribbean",
    "Wallis and Futuna": "https://www.usgs.gov/centers/national-minerals-information-center/asia-and-pacific#wlf",
    "Western Sahara": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#esh",
    "Yemen": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#yem",
    "Zambia": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#zmb",
    "Zimbabwe": "https://www.usgs.gov/centers/national-minerals-information-center/africa-and-middle-east#zwe",
}

# NMIC Volume III - Pseudo Countries List
pseudo_country_triggers = [
    "Regional Summaries",
    "Regional Summary",
    "Middle East Summary",
    "Africa Summary",
    "Asia and the Pacific Summary",
    "Europe and Central Eurasia Summary",
    "Caribbean Islands",
    "Central America"
]

# NMIC Volume III - Pseudo Country Groupings
pseudo_country_groups = {
    "Caribbean Islands": [
        "Antigua and Barbuda",
        "Aruba",
        "The Bahamas",
        "Barbados",
        "Curaçao",
        "Dominica",
        "Dominican Republic",
        "Grenada",
        "Guadeloupe",
        "Haiti",
        "Jamaica",
        "Martinique",
        "Montserrat"
    ],
    "Central America": [
        "Belize",
        "El Salvador",
        "Guatemala",
        "Honduras",
        "Panama",
        "Saint Kitts & Nevis",
        "Saint Lucia",
        "Saint Vincent & The Grenadines",
        "Trinidad & Tobago"
    ]
}